# Generated by Django 4.1.7 on 2023-12-29 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_outlet', '0006_address_author_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address Entries'},
        ),
    ]
