# Generated by Django 4.1.7 on 2023-12-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_outlet', '0007_alter_address_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='published_countries',
            field=models.ManyToManyField(to='product_outlet.country'),
        ),
    ]
