# Generated by Django 4.1.7 on 2024-01-03 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_outlet', '0008_country_book_published_countries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
